LABELS = {
    "boundary_descriptions": ("الحدود", "Boundaries"),
    "boundary_lengths": ("الأطوال", "Lengths"),
    "boundaries_continued": (
        "تفاصيل الحدود والأطوال في الصفحة التابعة للعقار",
        "Full boundaries and lengths follow this property",
    ),
    "contact_information": ("معلومات التواصل", "Contact information"),
    "property_links": ("روابط العقار", "Property links"),
    "summary": ("بيان العقارات", "Property summary"),
    "property_type": ("نوع العقار", "Property type"),
    "city": ("المدينة", "City"),
    "district": ("الحي", "District"),
    "usage": ("الاستخدام", "Usage"),
    "area": ("المساحة م²", "Area m²"),
    "area_short": ("المساحة م٢", "Area m²"),
    "deed_number": ("رقم الصك", "Deed number"),
    "plan_number": ("رقم المخطط", "Plan number"),
    "plot_number": ("رقم القطعة", "Plot number"),
    "execution_request_number": ("رقم طلب التنفيذ", "Execution request number"),
    "participation_amount": ("شيك الدخول", "Entry cheque"),
    "summary_type": ("نوع العقار", "Type"),
    "property_type_short": ("النوع", "Type"),
    "execution_short": ("رقم طلب التنفيذ", "Execution request"),
    "auction": ("مزاد", "Auction"),
    "held_at": ("يقام المزاد", "The auction is held"),
    "auction_hall": ("قاعة المزاد", "Auction hall"),
    "auction_platform": ("منصة المزاد", "Auction platform"),
    "scan_to_reach": (
        "إمسح على الباركود\nللوصول للموقع",
        "Scan the code\nto reach the site",
    ),
    "scan_to_enter": (
        "امسح او اضغط للدخول\nعلى المنصة الالكترونية",
        "Scan or tap to enter\nthe electronic platform",
    ),
    "platform_fallback": ("المنصة الإلكترونية", "the electronic platform"),
    "platform_name": ("إسم المنصة", "Platform"),
    "location": ("الموقع", "Location"),
    "recording_notice": (
        "سيتم توثيق / تصوير المزاد عبر الصور الفوتوغرافية والفيديو لأغراض التسويق والنشر.",
        "The auction will be documented in photographs and video for marketing and publication.",
    ),
    "closes": ("تغلق المزايدة\nعلى العقار", "Bidding on this\nproperty closes"),
    "property_number_in_booklet": (
        "رقم العقار في كتيب المزاد",
        "Property number in booklet",
    ),
    "deed_number_short": ("الصك رقم", "Deed number"),
    "property_name": ("إسم العقار", "Property name"),
    "rent_total": ("إجمالي قيمة\nالإيجار السنوي", "Total annual\nrent"),
    "rent_paid": (
        "المدة الإيجارية المسددة\nللمالك الحالي",
        "Period paid to\nthe current owner",
    ),
    "rent_next": ("الاستحقاق القادم\nلمبلغ الإيجار", "Next rent\ninstalment"),
    "click_link": ("أضغط هنا للوصول للرابط", "Open the link"),
    "auction_name": ("اسم المزاد", "Auction name"),
    "auction_type": ("نوع المزاد", "Auction type"),
    "physical": ("حضوري", "Physical"),
    "electronic": ("إلكتروني", "Electronic"),
    "hybrid": ("هجين", "Hybrid"),
    "auction_date": ("تاريخ المزاد", "Auction date"),
    "auction_start_date": ("تاريخ البداية", "Start date"),
    "auction_end_date": ("تاريخ النهاية", "End date"),
    "start_time": ("وقت البداية", "Start time"),
    "end_time": ("وقت النهاية", "End time"),
    "physical_location": ("موقع المزاد", "Physical location"),
    "electronic_platform_name": ("المنصة الإلكترونية", "Electronic platform"),
    "license_number": ("رقم الترخيص", "License number"),
    "supervising_authority": ("الجهة المشرفة", "Supervising authority"),
    "auction_contact_number": ("رقم التواصل", "Auction contact number"),
    "legal_announcement_text": ("الإعلان النظامي", "Legal announcement"),
    "court_decision_text": ("قرار المحكمة", "Court decision"),
    "description": ("وصف العقار", "Property description"),
    "notes": ("ملاحظات", "Notes"),
    "specifications": ("المواصفات", "Specifications"),
    "technical_information": ("معلومات فنية", "Technical information"),
    "additional_information": ("معلومات إضافية", "Additional information"),
    "features": ("مميزات العقار", "Property features"),
    "additional_images": ("صور إضافية", "Additional images"),
    "boundaries": ("أطوال وحدود العقار", "Property boundaries"),
    "north": ("شمالاً", "North"),
    "south": ("جنوباً", "South"),
    "east": ("شرقاً", "East"),
    "west": ("غرباً", "West"),
    "rental_contracts": ("بيان عقود الإيجار", "Rental contracts"),
    "unit_number": ("رقم\nالوحدة", "Unit\nnumber"),
    "contract_status": ("حالة\nالعقد", "Contract\nstatus"),
    "contract_start_date": ("تاريخ\nبداية العقد", "Contract\nstart"),
    "contract_end_date": ("تاريخ\nنهاية العقد", "Contract\nend"),
    "contract_duration": ("مدة\nالعقد", "Duration"),
    "paid_period": ("الفترة المسددة", "Paid period"),
    "next_due_date": ("الاستحقاق القادم", "Next due date"),
    "annual_rent_value": ("الإيجار السنوي", "Annual rent"),
    "auction_close_date": ("تاريخ إغلاق المزاد", "Closing date"),
    "auction_close_time": ("وقت إغلاق المزاد", "Closing time"),
    "survey_link": ("الرفع المساحي", "Survey"),
    "rental_information_link": ("معلومات الإيجار", "Rental information"),
    "additional_images_link": ("صور إضافية", "Additional images"),
    "location_link": ("موقع العقار", "Location"),
    "other_document_link": ("أضغط هنا للوصول للرابط", "Open the link"),
    "electronic_platform_url": ("منصة المزاد", "Auction platform"),
    "auction_location_url": ("موقع المزاد", "Auction location"),
    "booklet_url": ("كتيب المزاد", "Auction booklet"),
    "contact_url": ("التواصل", "Contact"),
    "contact": ("للتواصل والاستفسار", "Contact and enquiries"),
    "terms": ("شروط الدخول بالمزاد", "Auction terms"),
    "participation": (
        "خطوات المشاركة في المزاد الإلكتروني",
        "Electronic auction participation",
    ),
    "step_login": (
        "تسجيل الدخول في المنصة الإلكترونية",
        "Sign in to the electronic platform",
    ),
    "step_browse": ("استعراض المزادات", "Browse auctions"),
    "step_pay": (
        "سداد قيمة المشاركة في المزاد القابلة للاسترداد",
        "Pay the refundable participation amount",
    ),
    "step_select": (
        "اختيار المزاد والدخول للمشاركة",
        "Select the auction and participate",
    ),
    "step_win": ("الفوز بالمزاد", "Win the auction"),
    "DRAFT": ("مسودة", "Draft"),
    "APPROVED": ("معتمد", "Approved"),
    "NEEDS_REGENERATION": ("يتطلب إعادة توليد", "Needs regeneration"),
}


def label(key, language):
    return LABELS.get(key, (key, key))[0 if language == "ar" else 1]
